name: zakat_calculator
description: A sample command-line application.
version: 1.0.0
# homepage: https://github.com/fikrihandy/zakat_calculator

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  intl: ^0.18.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
